# Generated by Django 3.2.17 on 2023-02-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
    ]
